insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (1, 1, 1, 137.63, null, 3, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (2, 2, 2, 849.78, null, 5, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (3, 3, 3, 757.41, 'toaster', 5, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (4, 4, 4, 720.83, 'parking', 2, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (5, 5, 5, 541.81, 'breakfast', 8, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (6, 6, 1, 792.83, 'toaster', 8, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (7, 7, 2, 479.51, 'hot tub', 7, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (8, 8, 3, 131.71, 'toaster', 6, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (9, 9, 4, 776.39, null, 1, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (10, 10, 5, 232.36, 'kitchen', 5, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (11, 11, 1, 541.9, 'parking', 8, 'mountain', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (12, 12, 2, 157.61, 'toaster', 1, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (13, 13, 3, 608.3, 'parking', 1, 'mountain', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (14, 14, 4, 441.35, 'parking', 9, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (15, 15, 5, 371.72, null, 2, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (16, 16, 1, 646.93, 'toiletries', 6, 'sea', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (17, 17, 2, 602.5, 'toiletries', 3, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (18, 18, 3, 928.79, 'kitchen', 7, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (19, 19, 4, 430.47, 'hot tub', 4, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (20, 20, 5, 770.64, 'toiletries', 4, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (21, 21, 1, 629.78, 'breakfast', 2, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (22, 22, 2, 811.34, 'kitchen', 2, 'mountain', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (23, 23, 3, 155.28, 'hot tub', 6, 'mountain', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (24, 24, 4, 795.61, 'parking', 8, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (25, 25, 5, 775.64, 'toiletries', 8, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (26, 26, 1, 153.03, 'toaster', 9, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (27, 27, 2, 853.49, 'kitchen', 5, 'mountain', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (28, 28, 3, 210.58, 'parking', 9, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (29, 29, 4, 436.14, 'toiletries', 3, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (30, 30, 5, 100.86, 'breakfast', 5, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (31, 31, 1, 608.66, 'parking', 5, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (32, 32, 2, 720.9, 'kitchen', 5, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (33, 33, 3, 782.51, 'toiletries', 9, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (34, 34, 4, 443.98, 'toaster', 10, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (35, 35, 5, 752.4, 'hot tub', 3, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (36, 36, 1, 255.23, 'hot tub', 8, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (37, 37, 2, 403.25, 'kitchen', 8, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (38, 38, 3, 644.87, 'breakfast', 1, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (39, 39, 4, 806.06, 'bathrobe', 6, 'sea', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (40, 40, 5, 850.53, 'breakfast', 3, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (41, 1, 1, 426.5, 'bathrobe', 3, 'sea', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (42, 2, 2, 170.98, 'breakfast', 9, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (43, 3, 3, 554.97, 'bathrobe', 10, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (44, 4, 4, 474.56, 'parking', 4, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (45, 5, 5, 931.37, 'breakfast', 5, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (46, 6, 1, 493.82, 'parking', 5, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (47, 7, 2, 843.31, 'toiletries', 1, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (48, 8, 3, 974.51, 'bathrobe', 7, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (49, 9, 4, 368.87, 'hot tub', 5, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (50, 10, 5, 387.16, 'parking', 9, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (51, 11, 1, 686.4, 'hot tub', 5, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (52, 12, 2, 958.76, 'bathrobe', 7, 'sea', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (53, 13, 3, 467.42, 'toiletries', 3, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (54, 14, 4, 585.07, 'toiletries', 4, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (55, 15, 5, 687.34, 'breakfast', 3, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (56, 16, 1, 343.88, 'toiletries', 9, 'mountain', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (57, 17, 2, 223.77, 'parking', 9, 'mountain', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (58, 18, 3, 211.37, 'hot tub', 1, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (59, 19, 4, 753.38, 'parking', 4, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (60, 20, 5, 737.88, 'hot tub', 10, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (61, 21, 1, 754.0, 'toaster', 6, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (62, 22, 2, 501.99, 'kitchen', 1, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (63, 23, 3, 698.15, 'parking', 8, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (64, 24, 4, 459.55, 'parking', 7, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (65, 25, 5, 342.1, 'toaster', 5, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (66, 26, 1, 295.84, 'breakfast', 10, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (67, 27, 2, 283.28, 'toiletries', 5, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (68, 28, 3, 369.47, 'breakfast', 7, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (69, 29, 4, 925.55, 'toiletries', 8, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (70, 30, 5, 501.29, 'bathrobe', 3, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (71, 31, 1, 335.13, null, 9, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (72, 32, 2, 132.8, 'breakfast', 9, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (73, 33, 3, 607.38, 'breakfast', 8, 'sea', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (74, 34, 4, 342.56, 'toaster', 10, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (75, 35, 5, 871.46, 'hot tub', 2, 'sea', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (76, 36, 1, 509.95, 'bathrobe', 8, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (77, 37, 2, 794.16, 'hot tub', 5, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (78, 38, 3, 154.83, 'hot tub', 1, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (79, 39, 4, 215.96, 'hot tub', 4, 'mountain', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (80, 40, 5, 962.31, 'toaster', 4, 'mountain', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (81, 1, 1, 787.38, 'kitchen', 5, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (82, 2, 2, 748.93, 'breakfast', 9, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (83, 3, 3, 194.34, 'hot tub', 6, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (84, 4, 4, 329.06, 'toiletries', 4, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (85, 5, 5, 160.32, 'bathrobe', 2, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (86, 6, 1, 629.19, 'parking', 1, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (87, 7, 2, 334.57, 'parking', 9, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (88, 8, 3, 394.61, null, 1, 'sea', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (89, 9, 4, 272.98, 'kitchen', 8, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (90, 10, 5, 896.79, 'bathrobe', 8, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (91, 11, 1, 876.09, 'toaster', 4, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (92, 12, 2, 260.93, 'breakfast', 9, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (93, 13, 3, 900.14, 'toaster', 3, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (94, 14, 4, 308.59, 'kitchen', 1, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (95, 15, 5, 406.23, 'toaster', 7, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (96, 16, 1, 320.57, 'breakfast', 7, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (97, 17, 2, 574.46, 'parking', 8, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (98, 18, 3, 372.78, 'toaster', 8, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (99, 19, 4, 498.5, 'kitchen', 5, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (100, 20, 5, 121.76, 'hot tub', 4, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (101, 21, 1, 470.33, 'bathrobe', 1, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (102, 22, 2, 585.57, 'kitchen', 7, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (103, 23, 3, 360.41, 'hot tub', 2, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (104, 24, 4, 240.85, 'hot tub', 4, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (105, 25, 5, 315.14, 'bathrobe', 5, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (106, 26, 1, 596.04, 'toiletries', 6, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (107, 27, 2, 977.82, 'toaster', 1, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (108, 28, 3, 629.31, 'toiletries', 8, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (109, 29, 4, 913.56, 'breakfast', 5, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (110, 30, 5, 625.18, 'toaster', 4, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (111, 31, 1, 443.56, 'parking', 1, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (112, 32, 2, 151.98, 'toiletries', 7, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (113, 33, 3, 587.94, 'breakfast', 1, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (114, 34, 4, 557.72, 'bathrobe', 6, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (115, 35, 5, 303.71, 'breakfast', 1, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (116, 36, 1, 739.13, 'toaster', 5, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (117, 37, 2, 208.3, 'hot tub', 2, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (118, 38, 3, 199.74, 'toiletries', 9, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (119, 39, 4, 366.03, 'kitchen', 5, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (120, 40, 5, 243.51, 'toiletries', 5, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (121, 1, 1, 601.32, 'parking', 8, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (122, 2, 2, 839.21, 'parking', 10, 'sea', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (123, 3, 3, 921.63, 'parking', 8, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (124, 4, 4, 212.45, 'toaster', 8, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (125, 5, 5, 516.38, 'breakfast', 5, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (126, 6, 1, 567.19, 'toiletries', 4, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (127, 7, 2, 939.12, 'bathrobe', 5, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (128, 8, 3, 928.49, 'kitchen', 2, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (129, 9, 4, 183.28, 'breakfast', 2, 'sea', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (130, 10, 5, 693.46, 'kitchen', 10, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (131, 11, 1, 964.93, 'breakfast', 8, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (132, 12, 2, 431.15, 'bathrobe', 5, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (133, 13, 3, 647.47, 'parking', 9, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (134, 14, 4, 859.79, 'toiletries', 6, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (135, 15, 5, 110.62, 'hot tub', 10, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (136, 16, 1, 763.65, 'hot tub', 4, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (137, 17, 2, 509.43, 'hot tub', 10, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (138, 18, 3, 386.48, 'parking', 6, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (139, 19, 4, 510.24, 'parking', 3, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (140, 20, 5, 766.93, 'hot tub', 7, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (141, 21, 1, 370.06, 'toaster', 6, 'mountain', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (142, 22, 2, 690.72, 'kitchen', 4, 'sea', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (143, 23, 3, 968.89, 'kitchen', 5, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (144, 24, 4, 968.99, 'toaster', 4, 'sea', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (145, 25, 5, 362.05, 'bathrobe', 10, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (146, 26, 1, 135.64, 'kitchen', 4, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (147, 27, 2, 815.69, 'kitchen', 8, null, false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (148, 28, 3, 582.6, 'parking', 5, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (149, 29, 4, 414.33, 'parking', 3, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (150, 30, 5, 460.89, 'hot tub', 2, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (151, 31, 1, 529.24, 'parking', 1, 'mountain', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (152, 32, 2, 948.68, 'toiletries', 6, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (153, 33, 3, 262.79, 'kitchen', 2, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (154, 34, 4, 431.94, 'hot tub', 7, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (155, 35, 5, 702.92, 'breakfast', 1, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (156, 36, 1, 517.55, 'kitchen', 5, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (157, 37, 2, 531.64, 'bathrobe', 2, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (158, 38, 3, 644.1, 'breakfast', 8, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (159, 39, 4, 377.45, 'parking', 6, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (160, 40, 5, 531.07, 'parking', 1, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (161, 1, 1, 298.81, 'breakfast', 10, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (162, 2, 2, 563.46, 'parking', 4, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (163, 3, 3, 278.25, 'kitchen', 4, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (164, 4, 4, 929.73, 'breakfast', 1, 'sea', false, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (165, 5, 5, 981.25, 'bathrobe', 3, 'mountain', true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (166, 6, 1, 827.36, 'toiletries', 6, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (167, 7, 2, 489.99, null, 2, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (168, 8, 3, 698.23, 'bathrobe', 2, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (169, 9, 4, 214.64, 'toiletries', 1, 'mountain', true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (170, 10, 5, 341.18, 'toaster', 7, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (171, 11, 1, 135.13, 'hot tub', 3, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (172, 12, 2, 700.82, 'hot tub', 8, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (173, 13, 3, 763.27, 'kitchen', 4, 'sea', true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (174, 14, 4, 811.16, 'toaster', 2, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (175, 15, 5, 948.81, 'toaster', 1, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (176, 16, 1, 974.88, 'breakfast', 10, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (177, 17, 2, 862.15, 'kitchen', 5, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (178, 18, 3, 433.35, null, 6, 'mountain', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (179, 19, 4, 639.87, 'toaster', 1, 'mountain', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (180, 20, 5, 260.37, 'toaster', 8, null, true, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (181, 21, 1, 355.62, 'toiletries', 10, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (182, 22, 2, 261.71, 'bathrobe', 6, 'sea', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (183, 23, 3, 662.24, 'toiletries', 4, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (184, 24, 4, 970.75, null, 9, null, false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (185, 25, 5, 408.73, 'parking', 1, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (186, 26, 1, 115.77, 'hot tub', 5, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (187, 27, 2, 988.94, 'breakfast', 10, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (188, 28, 3, 903.84, 'bathrobe', 3, 'sea', false, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (189, 29, 4, 383.85, 'kitchen', 10, null, true, false, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (190, 30, 5, 239.24, 'toiletries', 2, 'sea', true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (191, 31, 1, 832.42, 'bathrobe', 2, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (192, 32, 2, 356.36, 'toiletries', 1, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (193, 33, 3, 851.26, 'breakfast', 8, 'sea', false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (194, 34, 4, 686.07, 'bathrobe', 10, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (195, 35, 5, 526.72, 'breakfast', 1, 'mountain', false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (196, 36, 1, 697.89, 'hot tub', 7, null, false, true, false);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (197, 37, 2, 317.73, 'kitchen', 1, null, true, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (198, 38, 3, 209.92, 'toiletries', 2, null, true, true, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (199, 39, 4, 529.81, 'hot tub', 9, null, false, false, true);
insert into room (id, hotel_id, hotel_chain_id, price, amenities, capacity, room_view, extendable, problems, status) values (200, 40, 5, 612.54, 'toiletries', 9, 'sea', false, false, true);
